### ISSUE TITLE
Unicode symbol in example?

### ISSUE THREAD

**Issue by benoliver999** [vincent-petithory/i3cat#3]
Hello - I really like your example script for showing mpd-now playing.

However, there's a couple of weird symbols that don't show on my PC.

It's the three that come after `status` so

    status=
    status=
    status=

And also

    full_text": "

(the final character is the one that won't show on my end)

They also bug out in i3bar when it loads. The codes seem to be `U+F04D`, `U+F04C`, (twice?) and `U+F198`

This probably seems like a crazy question, especially if you can see the fonts! I was just wondering what you were getting at, and what I might need to install?

**Comment by vincent-petithory** [comment]
Heya,

These chars are for iconic fonts, like font-awesome or font-icons.
The expected icons in this example are the standard play/pause/stop icons of music players.

Checkout https://wiki.archlinux.org/index.php/I3#Iconic_fonts_in_the_status_bar for example.
Note the codes for a particular icon may vary from one font to another.

**Comment by benoliver999** [comment]
Oh cool - I had no idea those were a thing on the desktop.
